logger:
  level: info
  filePath: /tmp/relayer/log/relayer.log
  logToConsole: false
  logToFile: true
db:
  badger:
    core:
      gcIntervalSeconds: 10
      scanRangeThreshold: 3000
      maxScanIterators: 10000
      filterTtlMinutes: 15
      options:
        Dir: /tmp/relayer/data
        InMemory: false
        DetectConflicts: false
endpoint:
  chainID: 1313161554
  filterFilePath: config/filter.yaml
  engine:
    nearNetworkID: mainnet
    nearNodeURL: https://archival-rpc.mainnet.near.org
    signer:
    signerKey:
    asyncSendRawTxs: false
    minGasPrice: 0
    minGasLimit: 21000
    gasForNearTxsCall: 300000000000000
    depositForNearTxsCall: 0
    retryWaitTimeMsForNearTxsCall: 3000
    retryNumberForNearTxsCall: 3
  eth:
    protocolVersion: 0x41
    hashrate: 0
    gas: 6721975
  proxyEndpoints:
    url: "https://mainnet.aurora.dev:443"
    endpoints:
    -
  disabledEndpoints:
    -
rpcNode:
  geth:
    HTTPHost: localhost
    HTTPPort: 8545
    HTTPVirtualHosts:
      - localhost
    HTTPModules:
      - "net"
      - "web3"
      - "eth"
    WSHost: localhost
    WSPort: 8545
    WSModules:
      - "net"
      - "web3"
      - "eth"
indexer:
  sourceFolder: /tmp/relayer/json/
  subFolderBatchSize: 10000   # should match with Aurora refiner batch size, see https://github.com/aurora-is-near/borealis-engine-lib
  keepFiles: true
  genesisBlock: 9820210       # 9820210 = Aurora Genesis
  fromBlock: 9820210          # cannot be lower than Genesis
  toBlock: 0                  # 0 = indefinite
  retryCountOnFailure: 10
  waitForBlocksMs: 500
