logger:
  level: info
  filePath: /tmp/relayer/log/relayer.log
  logToConsole: true
  logToFile: true
db:
  badger:
    core:
      gcIntervalSeconds: 10
      scanRangeThreshold: 3000
      maxScanIterators: 10000
      filterTtlMinutes: 15
      options:
        Dir: /tmp/relayer/data
        InMemory: false
        DetectConflicts: false
endpoint:
  chainID: 1313161554
  engine:
    nearNetworkID: testnet
    nearNodeURL: https://archival-rpc.testnet.near.org
    signer:
    signerKey:
    asyncSendRawTxs: false
    minGasPrice: 0
    minGasLimit: 21000
    gasForNearTxsCall: 300000000000000
    depositForNearTxsCall: 0
    retryWaitTimeMsForNearTxsCall: 3000
    retryNumberForNearTxsCall: 3
  eth:
    protocolVersion: 0x41
    hashrate: 0
    gas: 6721975
  proxyEndpoints:
    url: "https://testnet.aurora.dev:443"
    endpoints:
    -
  disabledEndpoints:
    -
rpcNode:
  geth:
    HTTPHost: localhost
    HTTPPort: 8545
    HTTPVirtualHosts:
      - localhost
    HTTPModules:
      - "net"
      - "web3"
      - "eth"
    WSHost: localhost
    WSPort: 8545
    WSModules:
      - "net"
      - "web3"
      - "eth"
indexer:
  sourceFolder: "../borealis-engine-lib/output/refiner"
  subFolderBatchSize: 10000
  keepFiles: false
